### ISSUE TITLE
Exception has occurred. MissingPluginException (MissingPluginException(No implementation found for method controlVolume on channel volume))

### ISSUE THREAD

**Issue by saqibcare** [januwA/flutter_video_box#13]
While testing on ios, i got the following exception in initializer. 

```
Exception has occurred.
MissingPluginException (MissingPluginException(No implementation found for method controlVolume on channel volume))
```
```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.13.1-pre.15, on Mac OS X 10.15.1 19B88, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] Connected device (4 available)

• No issues found!
```

**Comment by januwA** [comment]
@saqibcare  Hi, I think this error is caused by the use of the [volume](https://pub.dev/packages/volume) plugin, because this plugin does not provide IOS support, you can pull the source code and delete this plugin and related code. I do n’t have IOS and MAC equipment, so I ca n’t do related development, sorry.

**Comment by januwA** [comment]
In the `v0.9.1` version, I removed some possible platform differences. If you are interested, you can take a look
